spring:
  cloud:
    gateway:
      routes:
        - id: baiduRoute
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qqRoute
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
server:
  port: 12345


